[workspace]
members = [
	"ingert",
	"ingert-syntax",
	"ingert-cli",
]
resolver = "3"

[workspace.package]
version = "1.1.2"

[workspace.dependencies]
indexmap = "2.8.0"

[profile.dev.package."*"]
opt-level = 3
