[package]
name = "ingert"
version.workspace = true
edition = "2024"

[dependencies]
gospel = "0.3.1"
snafu = "0.8.5"
tracing = { version = "0.1.40", features = ["attributes"] }
crc32fast = "1.4.2"
strum = { version = "0.26", features = ["derive"] }
indexmap.workspace = true
